#!/usr/bin/env python3
"""Export fixed Alloy sources and check a consumer's resolved package paths."""

import argparse
import hashlib
import io
import json
import os
import posixpath
import re
import subprocess
import tempfile
import tomllib
from pathlib import Path

ROOTS = ("crates/gpui", "crates/gpui_platform")
RECORD = "ALLOY-SNAPSHOT.json"
SOURCE_RECORD = "ALLOY-SOURCE.json"
ORIGINAL_RECORD = "alloy-source/ALLOY-SNAPSHOT.json"
PROVENANCE = (
    SOURCE_RECORD,
    ORIGINAL_RECORD,
    "alloy-source/Cargo.toml",
    "alloy-source/Cargo.lock",
    "alloy-source/.cargo/config.toml",
    "alloy-source/rust-toolchain.toml",
)


def git(repo, *arguments, **kwargs):
    return subprocess.check_output(
        ["git", "--no-replace-objects", "-C", str(repo), *arguments], **kwargs
    )


def blob(repo, revision, path):
    return git(repo, "cat-file", "blob", f"{revision}:{path}")


def check_commit(repo, revision):
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError("Use a full lowercase Git commit SHA.")
    if git(repo, "rev-parse", f"{revision}^{{commit}}").decode().strip() != revision:
        raise ValueError(f"Expected a commit: {revision}")


def dependencies(manifest):
    for table in (manifest, *manifest.get("target", {}).values()):
        for kind in ("dependencies", "build-dependencies", "dev-dependencies"):
            yield from table.get(kind, {}).items()


def closure(repo, revision, workspace):
    packages = {}
    members = set()
    inherited = set()
    pending = list(ROOTS)
    while pending:
        directory = pending.pop()
        if directory in members:
            continue
        members.add(directory)
        manifest = tomllib.loads(blob(repo, revision, f"{directory}/Cargo.toml").decode())
        name = manifest["package"]["name"]
        if name in packages:
            raise ValueError(f"Duplicate package name: {name}")
        packages[name] = f"{directory}/Cargo.toml"
        for name, dependency in dependencies(manifest):
            base = directory
            if isinstance(dependency, dict) and dependency.get("workspace"):
                inherited.add(name)
                dependency = workspace["dependencies"][name]
                base = "."
            if isinstance(dependency, dict) and "path" in dependency:
                path = posixpath.normpath(posixpath.join(base, dependency["path"]))
                if path.startswith(("/", "../")) or path in (".", ".."):
                    raise ValueError(f"Dependency path leaves the crate tree: {path}")
                pending.append(path)
    return sorted(members), dict(sorted(packages.items())), inherited


def toml_value(value):
    if isinstance(value, (str, bool, int, float)):
        return json.dumps(value, ensure_ascii=False, allow_nan=False)
    if isinstance(value, list):
        return "[" + ", ".join(map(toml_value, value)) + "]"
    if isinstance(value, dict):
        return (
            "{ " + ", ".join(f"{json.dumps(k)} = {toml_value(v)}" for k, v in value.items()) + " }"
        )
    raise ValueError(f"Unsupported workspace TOML value: {type(value).__name__}")


def workspace_manifest(workspace, members, inherited):
    extracted = {"resolver": workspace["resolver"], "members": members}
    for key in ("package", "dependencies", "lints"):
        if key in workspace:
            extracted[key] = workspace[key]
    extracted["dependencies"] = {
        name: workspace["dependencies"][name] for name in sorted(inherited)
    }
    sections = ["# Generated by script/gpui_snapshot.py.\n[workspace]"]
    for key, value in extracted.items():
        if isinstance(value, dict):
            sections.append(f"\n[workspace.{key}]")
            sections.extend(f"{json.dumps(k)} = {toml_value(v)}" for k, v in value.items())
        else:
            sections.append(f"{key} = {toml_value(value)}")
    result = "\n".join(sections) + "\n"
    if tomllib.loads(result) != {"workspace": extracted}:
        raise ValueError("Generated workspace manifest does not preserve the selected values.")
    return result


def inventory(directory):
    result = {}
    for path in sorted(directory.rglob("*")):
        relative = path.relative_to(directory).as_posix()
        if relative == RECORD:
            continue
        if path.is_symlink():
            content = os.readlink(path).encode()
            kind = "symlink"
        elif path.is_file():
            content = path.read_bytes()
            kind = "file"
        elif path.is_dir():
            continue
        else:
            raise ValueError(f"Unsupported snapshot entry: {path}")
        result[relative] = {
            "type": kind,
            "executable": bool(path.lstat().st_mode & 0o111),
            "sha256": hashlib.sha256(content).hexdigest(),
        }
    return result


def export_tree(repo, revision, selected, output):
    entries = []
    for entry in git(repo, "ls-tree", "-r", "-z", revision, "--", *selected).split(b"\0"):
        if entry:
            information, path = entry.split(b"\t", 1)
            mode, kind, object_id = information.split()
            if kind != b"blob" or mode not in (b"100644", b"100755", b"120000"):
                raise ValueError(f"Unsupported Git tree entry: {path!r}")
            entries.append((mode, object_id, path.decode()))
    for selected_path in selected:
        if not any(
            path == selected_path or path.startswith(selected_path + "/") for _, _, path in entries
        ):
            raise ValueError(f"Required source path is missing: {selected_path}")
    objects = io.BytesIO(
        git(repo, "cat-file", "--batch", input=b"\n".join(entry[1] for entry in entries) + b"\n")
    )
    output.mkdir()
    for mode, object_id, path in entries:
        actual_id, kind, size = objects.readline().split()
        if actual_id != object_id or kind != b"blob":
            raise ValueError(f"Unexpected Git blob response for {path}")
        content = objects.read(int(size))
        if objects.read(1) != b"\n":
            raise ValueError(f"Incomplete Git blob response for {path}")
        destination = output / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        if mode == b"120000":
            target = content.decode()
            resolved = posixpath.normpath(posixpath.join(posixpath.dirname(path), target))
            if resolved.startswith(("/", "../")) or resolved == "..":
                raise ValueError(f"Symlink leaves the snapshot: {path}")
            destination.symlink_to(target)
        else:
            destination.write_bytes(content)
            destination.chmod(0o755 if mode == b"100755" else 0o644)


def source_provenance(repo, revision):
    source = json.loads(blob(repo, revision, SOURCE_RECORD))
    if source["format"] != 1 or source["kind"] != "standalone-source":
        raise ValueError("Unsupported standalone source record.")
    for key in ("upstream", "revision"):
        if not re.fullmatch(r"[0-9a-f]{40}", source[key]):
            raise ValueError(f"Use a full lowercase source {key} SHA.")
    original_bytes = blob(repo, revision, ORIGINAL_RECORD)
    if hashlib.sha256(original_bytes).hexdigest() != source["snapshot_sha256"]:
        raise ValueError("Original source record differs from its recorded SHA-256.")
    original = json.loads(original_bytes)
    if (
        original["format"] != 1
        or original["roots"] != list(ROOTS)
        or any(original[key] != source[key] for key in ("upstream", "revision"))
    ):
        raise ValueError("Original source record does not match standalone provenance.")
    return source, original


def export_snapshot(repo, revision, output):
    check_commit(repo, revision)
    source, original = source_provenance(repo, revision)
    workspace = tomllib.loads(blob(repo, revision, "Cargo.toml").decode())["workspace"]
    members, packages, inherited = closure(repo, revision, workspace)
    if packages != original["packages"]:
        raise ValueError("Standalone package closure differs from its source record.")
    manifest = workspace_manifest(workspace, members, inherited)
    selected = [*members, "assets/fonts", "LICENSE-APACHE", "LICENSE-GPL", *PROVENANCE]
    export_tree(repo, revision, selected, output)
    actual = inventory(output)
    for path in (SOURCE_RECORD, ORIGINAL_RECORD):
        del actual[path]
    preserved = {
        path: entry
        for path, entry in original["files"].items()
        if path not in ("Cargo.toml", "README.md")
    }
    if actual != preserved:
        raise ValueError("Standalone source files differ from the original export inventory.")
    (output / "Cargo.toml").write_text(manifest, encoding="utf-8", newline="\n")
    (output / "README.md").write_text(
        f"# GPUI Alloy source export\n\nStandalone revision: `{revision}`.\n\n"
        f"Original integration: `{source['revision']}` from {source['repository']}.\n\n"
        f"Upstream baseline: `{source['upstream']}`.\n\n"
        "This directory contains generated sources. Source verification does not establish build or native behavior. "
        "Keep the directory unchanged and retain `ALLOY-SNAPSHOT.json`. "
        "The consumer configuration and lockfile control external dependencies. "
        "Original workspace controls and the original export record are preserved under `alloy-source/`. "
        "The standalone commit has independent Git history.\n\n"
        "See the [maintenance policy](https://github.com/AprilNEA/gpui-alloy/blob/main/ALLOY.md). "
        "Each crate retains its upstream license.\n",
        encoding="utf-8",
        newline="\n",
    )
    record = {
        "format": 2,
        "revision": revision,
        "source": source,
        "exporter_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "roots": list(ROOTS),
        "packages": packages,
        "policy": {
            "closure": "All path dependencies, including optional, target, build and dev dependencies.",
            "workspace": "Keep resolver, package, used dependencies and lints; replace members. Generate README.md.",
            "sources": "Keep complete crate directories, assets/fonts and root licenses unchanged.",
            "provenance": "Keep ALLOY-SOURCE.json and original export provenance unchanged; do not activate original controls.",
            "resolution": "The consumer root configuration and Cargo.lock control external dependencies.",
        },
        "files": inventory(output),
    }
    (output / RECORD).write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    return record


def verify_snapshot(repo, revision, snapshot):
    with tempfile.TemporaryDirectory(prefix="alloy-verify-") as temporary:
        expected = export_snapshot(repo, revision, Path(temporary) / "snapshot")
    actual = inventory(snapshot)
    differences = sorted(
        path
        for path in actual.keys() | expected["files"].keys()
        if actual.get(path) != expected["files"].get(path)
    )
    if differences:
        raise ValueError("Snapshot files differ from Git: " + ", ".join(differences[:10]))
    if json.loads((snapshot / RECORD).read_text(encoding="utf-8")) != expected:
        raise ValueError("Snapshot record differs from the expected Git revision or exporter.")
    return expected


def verify_resolution(metadata, consumer, snapshot, record):
    if Path(metadata["workspace_root"]).resolve() != consumer.resolve():
        raise ValueError("Cargo metadata does not describe the requested consumer workspace.")
    if metadata["resolve"] is None:
        raise ValueError("Cargo metadata must include the dependency graph.")
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    packages = {package["id"]: package for package in metadata["packages"]}
    pending = list(metadata["workspace_members"])
    reached = set()
    checked = set()
    while pending:
        package_id = pending.pop()
        if package_id in reached:
            continue
        reached.add(package_id)
        pending.extend(dependency["pkg"] for dependency in nodes[package_id]["deps"])
        package = packages[package_id]
        name = package["name"]
        if name not in record["packages"]:
            continue
        if name in checked:
            raise ValueError(f"Consumer resolves multiple package identities for {name}.")
        expected = (snapshot / record["packages"][name]).resolve()
        actual = Path(package["manifest_path"]).resolve()
        if package["source"] is not None or actual != expected:
            raise ValueError(f"Consumer resolves {name} outside the snapshot: {actual}")
        checked.add(name)
    if "gpui" not in checked:
        raise ValueError("Consumer does not resolve GPUI from the snapshot.")
    return len(checked)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("export", "verify-consumer"))
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--revision", required=True, help="Full standalone commit SHA (S)")
    parser.add_argument("--snapshot", required=True, type=Path)
    parser.add_argument("--consumer", type=Path, help="Consumer workspace root")
    parser.add_argument("--target", help="Cargo metadata target filter")
    arguments = parser.parse_args()
    if arguments.command == "export":
        if arguments.consumer or arguments.target:
            parser.error("--consumer and --target apply only to verify-consumer")
        record = export_snapshot(arguments.repo, arguments.revision, arguments.snapshot)
        print(f"Exported {len(record['packages'])} packages from {arguments.revision}.")
        return
    if arguments.consumer is None:
        parser.error("verify-consumer requires --consumer")
    record = verify_snapshot(arguments.repo, arguments.revision, arguments.snapshot)
    command = ["cargo", "metadata", "--format-version", "1", "--locked", "--all-features"]
    if arguments.target:
        command.extend(["--filter-platform", arguments.target])
    metadata = json.loads(subprocess.check_output(command, cwd=arguments.consumer))
    count = verify_resolution(metadata, arguments.consumer, arguments.snapshot, record)
    print(
        f"Verified snapshot {arguments.revision} and {count} resolved packages; "
        f"target={arguments.target or 'all'}, features=all, lock=locked. "
        "Build and native behavior remain separate checks."
    )


if __name__ == "__main__":
    main()
