#!/usr/bin/env python3
"""Project a fixed Alloy snapshot into a reproducible registry staging workspace."""

import argparse
import copy
import difflib
import graphlib
import hashlib
import json
import posixpath
import re
import tomllib
from pathlib import Path

import gpui_snapshot as snapshot

RECORD = "ALLOY-REGISTRY.json"
PACKAGE_RECORD = "ALLOY-REGISTRY-SOURCE.json"
GIT_KEYS = ("git", "rev", "branch", "tag")
SHADER_INPUTS = ("scene.rs", "geometry.rs", "color.rs", "window.rs", "platform.rs")


def digest(value):
    content = value if isinstance(value, bytes) else json.dumps(value, sort_keys=True).encode()
    return hashlib.sha256(content).hexdigest()


def inventory(directory):
    result = snapshot.inventory(directory)
    # The source exporter excludes its own record; the registry projection must hash that input.
    path = directory / snapshot.RECORD
    if path.is_file():
        result[snapshot.RECORD] = {
            "type": "file",
            "executable": bool(path.stat().st_mode & 0o111),
            "sha256": digest(path.read_bytes()),
        }
    return result


def package_name(name):
    if name == "gpui":
        return "gpui-alloy"
    if name == "util":
        return "gpui-alloy-zed-util"
    suffix = name.removeprefix("gpui_").replace("_", "-")
    return f"gpui-alloy-{suffix}"


def render_manifest(manifest):
    # Inline tables reuse the snapshot serializer and preserve arbitrary nested metadata.
    result = (
        "# Generated by script/gpui_registry.py.\n"
        + "\n".join(
            f"{json.dumps(key)} = {snapshot.toml_value(value)}" for key, value in manifest.items()
        )
        + "\n"
    )
    if tomllib.loads(result) != manifest:
        raise ValueError("Generated registry manifest failed TOML round-trip verification.")
    return result


def manifest_change(before, after, path):
    return {
        "before_sha256": digest(before.encode()),
        "after_sha256": digest(after.encode()),
        "diff": "".join(
            difflib.unified_diff(
                before.splitlines(keepends=True),
                after.splitlines(keepends=True),
                fromfile=f"source/{path}",
                tofile=f"registry/{path}",
            )
        ),
    }


def dependency(name, value, workspace, directory, packages, version, overrides):
    value = {"version": value} if isinstance(value, str) else copy.deepcopy(value)
    base = directory
    if value.pop("workspace", False):
        inherited = workspace["dependencies"][name]
        inherited = (
            {"version": inherited} if isinstance(inherited, str) else copy.deepcopy(inherited)
        )
        features = list(dict.fromkeys(inherited.get("features", []) + value.pop("features", [])))
        inherited.update(value)
        value = inherited
        if features:
            value["features"] = features
        base = "."
    if "path" in value:
        path = posixpath.normpath(posixpath.join(base, value["path"]))
        original = next(
            (name for name, entry in packages.items() if entry["directory"] == path), None
        )
        if original is None:
            raise ValueError(f"Unrecorded internal dependency {name}: {path}")
        value.update(package=packages[original]["package"], version=f"={version}")
        value["path"] = posixpath.relpath(path, directory)
        return value, original
    if "git" in value:
        override = overrides.get(name)
        identity = {key: value[key] for key in GIT_KEYS if key in value}
        if override is None or override.get("source") != identity:
            raise ValueError(
                f"Audit a registry replacement for Git dependency {name}: {identity}; "
                "provide its exact source and registry package/version in --git-overrides."
            )
        internal = override.get("internal")
        if internal:
            entry = packages[internal]
            if entry.get("source") != identity:
                raise ValueError(f"Fixed-source member does not match Git dependency {name}.")
            for key in GIT_KEYS:
                value.pop(key, None)
            value.update(package=entry["package"], version=f"={version}")
            value["path"] = posixpath.relpath(entry["directory"], directory)
            return value, internal
        replacement = override["registry"]
        if not replacement.get("version"):
            raise ValueError(f"Registry replacement for {name} requires a version.")
        if value.get("version", "").startswith("=") and value["version"] != replacement["version"]:
            raise ValueError(f"Registry replacement must preserve exact version pin for {name}.")
        if set(replacement) - {"package", "version"}:
            raise ValueError(
                f"Registry replacement for {name} may change only package and version."
            )
        for key in GIT_KEYS:
            value.pop(key, None)
        value.update(replacement)
    return value, None


def project_manifest(original, workspace, directory, packages, version, overrides):
    result = copy.deepcopy(original)
    package = result["package"]
    name = package["name"]
    for key, value in list(package.items()):
        if isinstance(value, dict) and value.get("workspace") is True:
            package[key] = copy.deepcopy(workspace["package"][key])
    package.update(
        name=packages[name]["package"],
        version=version,
        publish=True,
        repository="https://github.com/AprilNEA/gpui-alloy",
        autoexamples=False,
        autotests=False,
        autobenches=False,
    )
    package.setdefault("description", f"GPUI Alloy distribution of {name}")
    if "include" in package:
        package["include"].append(f"/{PACKAGE_RECORD}")
    elif "exclude" in package:
        package["exclude"].append(f"!/{PACKAGE_RECORD}")
    result.setdefault("lib", {}).setdefault("name", name.replace("-", "_"))
    result["lib"].update(test=False, doctest=False, bench=False)
    for kind in ("example", "test", "bench"):
        result.pop(kind, None)
    if result.get("lints", {}).get("workspace"):
        result["lints"] = copy.deepcopy(workspace["lints"])
    reached = set()
    for table in (result, *result.get("target", {}).values()):
        table.pop("dev-dependencies", None)
        for kind in ("dependencies", "build-dependencies"):
            for dep_name, value in table.get(kind, {}).items():
                resolved, internal = dependency(
                    dep_name, value, workspace, directory, packages, version, overrides
                )
                table[kind][dep_name] = resolved
                if internal:
                    reached.add(internal)
    return result, reached


def materialize_links(output, directories):
    changes = {}
    # Nested packages own their links; process the deepest package first.
    for directory in sorted(directories, key=lambda path: (-len(Path(path).parts), path)):
        root = output / directory
        for path in sorted(root.rglob("*")):
            if not path.is_symlink():
                continue
            target = path.resolve(strict=True)
            if not target.is_relative_to(output.resolve()):
                raise ValueError(f"Package symlink leaves the staging workspace: {path}")
            if target.is_relative_to(root.resolve()):
                continue
            if not target.is_file():
                raise ValueError(f"Package-external symlink must target a file: {path}")
            content = target.read_bytes()
            relative = path.relative_to(output).as_posix()
            changes[relative] = {"target": path.readlink().as_posix(), "sha256": digest(content)}
            path.unlink()
            path.write_bytes(content)
    return changes


def adapt_apple_build(output):
    path = output / "crates/gpui_apple/build.rs"
    before = path.read_bytes()
    old, new = b'.join("../gpui")', b'.join("vendor/gpui")'
    if before.count(old) != 1:
        raise ValueError("Expected exactly one relative GPUI lookup in the Apple build script.")
    after = before.replace(old, new)
    path.write_bytes(after)
    copied = {}
    for name in SHADER_INPUTS:
        source = output / "crates/gpui/src" / name
        destination = output / "crates/gpui_apple/vendor/gpui/src" / name
        if destination.exists():
            raise ValueError(f"Build adapter destination already exists: {destination}")
        destination.parent.mkdir(parents=True, exist_ok=True)
        content = source.read_bytes()
        destination.write_bytes(content)
        copied[destination.relative_to(output).as_posix()] = {
            "source": source.relative_to(output).as_posix(),
            "sha256": digest(content),
        }
    return {
        "path": "crates/gpui_apple/build.rs",
        "before_sha256": digest(before),
        "after_sha256": digest(after),
        "diff": "".join(
            difflib.unified_diff(
                before.decode().splitlines(keepends=True),
                after.decode().splitlines(keepends=True),
                fromfile="source/crates/gpui_apple/build.rs",
                tofile="registry/crates/gpui_apple/build.rs",
            )
        ),
        "copied_inputs": copied,
    }


def export_extra_members(output, extra_members):
    packages, records = {}, {}
    for member in extra_members:
        repo, revision = Path(member["repo"]), member["revision"]
        snapshot.check_commit(repo, revision)
        original = tomllib.loads(snapshot.blob(repo, revision, "Cargo.toml").decode())
        name = original["package"]["name"]
        directory = f"external/{member['package']}"
        if not re.fullmatch(r"gpui-alloy-[a-z0-9-]+", member["package"]):
            raise ValueError(f"Invalid external registry package: {member['package']}")
        (output / "external").mkdir(exist_ok=True)
        selected = snapshot.git(repo, "ls-tree", "--name-only", revision).decode().splitlines()
        snapshot.export_tree(repo, revision, selected, output / directory)
        source = {"git": member["repository"], "rev": revision}
        packages[name] = {
            "package": member["package"],
            "directory": directory,
            "manifest": f"{directory}/Cargo.toml",
            "source": source,
        }
        records[name] = {"source": source, "files": inventory(output / directory)}
    return packages, records


def project_registry(repo, revision, version, output, overrides, extra_members=()):
    if not re.fullmatch(r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?", version):
        raise ValueError("Use a release or prerelease version without build metadata.")
    if output.exists():
        raise ValueError(f"Registry staging directory must not exist: {output}")
    source = snapshot.export_snapshot(repo, revision, output)
    original_workspace = tomllib.loads(snapshot.blob(repo, revision, "Cargo.toml").decode())
    before_workspace = (output / "Cargo.toml").read_text()
    workspace = tomllib.loads((output / "Cargo.toml").read_text())["workspace"]
    packages = {
        name: {"package": package_name(name), "directory": str(Path(path).parent), "manifest": path}
        for name, path in source["packages"].items()
    }
    extra_packages, extra_records = export_extra_members(output, extra_members)
    if packages.keys() & extra_packages.keys():
        raise ValueError("Fixed-source members duplicate standalone package names.")
    packages.update(extra_packages)
    source_files = inventory(output)
    if len({entry["package"] for entry in packages.values()}) != len(packages):
        raise ValueError("Registry package names collide.")
    manifests, graph = {}, {}
    for name, entry in packages.items():
        path = output / entry["manifest"]
        before = path.read_text()
        manifest, graph[name] = project_manifest(
            tomllib.loads(before),
            {} if name in extra_packages else workspace,
            entry["directory"],
            packages,
            version,
            overrides,
        )
        after = render_manifest(manifest)
        manifests[entry["manifest"]] = manifest_change(before, after, entry["manifest"])
        path.write_text(after, encoding="utf-8", newline="\n")
    order = list(
        graphlib.TopologicalSorter({k: sorted(v) for k, v in graph.items()}).static_order()
    )
    (output / "Cargo.toml").write_text(
        render_manifest(
            {
                "workspace": {
                    "resolver": workspace["resolver"],
                    "members": [entry["directory"] for entry in packages.values()],
                }
            }
        ),
        encoding="utf-8",
        newline="\n",
    )
    manifests["Cargo.toml"] = manifest_change(
        before_workspace, (output / "Cargo.toml").read_text(), "Cargo.toml"
    )
    links = materialize_links(output, [entry["directory"] for entry in packages.values()])
    adapter = adapt_apple_build(output)
    for name, entry in packages.items():
        record = {
            "format": 1,
            "suite_revision": revision,
            "version": version,
            "suite_source": source["source"],
            "package_source": entry.get("source")
            or {
                "git": "https://github.com/AprilNEA/gpui-alloy",
                "rev": revision,
                "path": entry["directory"],
            },
            "generator_sha256": digest(Path(__file__).read_bytes()),
            "snapshot_generator_sha256": source["exporter_sha256"],
            "original_package": name,
            "registry_package": entry["package"],
            "manifest": manifests[entry["manifest"]],
            "source_files": {
                p: v for p, v in source_files.items() if p.startswith(entry["directory"] + "/")
            },
            "build_adapter": adapter if name == "gpui_apple" else None,
            "git_overrides": overrides,
        }
        (output / entry["directory"] / PACKAGE_RECORD).write_text(
            json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
        )
    projected_files = inventory(output)
    record = {
        "format": 1,
        "kind": "registry-projection",
        "revision": revision,
        "version": version,
        "source": source["source"],
        "generator_sha256": digest(Path(__file__).read_bytes()),
        "snapshot_generator_sha256": source["exporter_sha256"],
        "external_sources": extra_records,
        "omitted_root_patches": original_workspace.get("patch", {}),
        "packages": packages,
        "publish_order": [packages[name]["package"] for name in order],
        "source_inventory_sha256": digest(source_files),
        "source_files": source_files,
        "files": projected_files,
        "projected_inventory_sha256": digest(projected_files),
        "manifests": manifests,
        "materialized_symlinks": links,
        "build_adapter": adapter,
        "git_overrides": overrides,
        "policy": {
            "manifests": "Resolve inheritance, namespace packages, preserve library names, and pin internal dependencies exactly.",
            "targets": "Omit dev dependencies and example, test, and bench targets in registry manifests only.",
            "sources": "Preserve runtime source bytes. Adapt only the recorded Apple build-script input lookup.",
            "patches": "Do not activate root Git patches in the registry projection.",
            "validation": "This record proves projection provenance, not registry availability or consumer compatibility.",
        },
    }
    (output / RECORD).write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    return record


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--revision", required=True, help="Full fixed standalone commit SHA")
    parser.add_argument("--version", required=True)
    parser.add_argument("--output", type=Path, required=True, help="New staging directory")
    parser.add_argument(
        "--git-overrides", type=Path, required=True, help="Audited source-to-registry JSON mapping"
    )
    parser.add_argument("--extra-members", type=Path, help="Fixed external Git sources as JSON")
    args = parser.parse_args()
    record = project_registry(
        args.repo,
        args.revision,
        args.version,
        args.output,
        json.loads(args.git_overrides.read_text()),
        json.loads(args.extra_members.read_text()) if args.extra_members else (),
    )
    print(
        f"Projected {len(record['packages'])} packages at {args.version}; publication remains a separate action."
    )


if __name__ == "__main__":
    main()
